package com.sourcefish.tools;

public enum Tasks {
	NEWENTRY, 
	STOPENTRY,
	NEWPROJECT,
	UPDATEUSER, 
	GETUSERDATA, 
	MANUALENTRY, 
	DELETEENTRY,
	ADDUSERTOPROJECT,
	DELETEPROJECT,
	EDITPROJECT,
	LEAVEPROJECT
}
